/**
 * Company API Route - TalentHR
 * Handles company information and settings
 */

import { NextRequest, NextResponse } from "next/server";
import connectDB from "@/lib/db";
import Company from "@/models/Company";
import { authenticateRequest } from "@/lib/auth-middleware";
import { z } from "zod";

const updateCompanySchema = z.object({
  name: z.string().min(2, "Company name must be at least 2 characters").optional(),
  domain: z.string().optional(),
  settings: z
    .object({
      timezone: z.string().optional(),
      currency: z.string().optional(),
      dateFormat: z.string().optional(),
    })
    .optional(),
});

/**
 * GET /api/company
 * Get company information
 */
export async function GET(request: NextRequest) {
  try {
    await connectDB();

    // Authenticate request
    const auth = await authenticateRequest(request);
    if (!auth.success) return auth.response;

    const { user } = auth.data;

    // Get company info
    const company = await Company.findById((user as any).companyId);

    if (!company) {
      return NextResponse.json(
        {
          success: false,
          message: "Company not found",
        },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      company: {
        id: String(company._id),
        name: company.name,
        slug: company.slug,
        domain: company.domain,
        status: company.status,
        settings: company.settings,
        subscription: company.subscription,
        createdAt: company.createdAt.toISOString(),
        updatedAt: company.updatedAt.toISOString(),
      },
    });
  } catch (error) {
    console.error("Get company error:", error);
    return NextResponse.json(
      {
        success: false,
        message:
          error instanceof Error ? error.message : "Internal server error",
      },
      { status: 500 }
    );
  }
}

/**
 * PUT /api/company
 * Update company information (Admin only)
 */
export async function PUT(request: NextRequest) {
  try {
    await connectDB();

    // Authenticate request
    const auth = await authenticateRequest(request);
    if (!auth.success) return auth.response;

    const { user } = auth.data;

    // Check permissions - only company admin can update
    if (user.role !== "company_admin") {
      return NextResponse.json(
        {
          success: false,
          message: "Only company administrators can update company settings",
        },
        { status: 403 }
      );
    }

    const body = await request.json();
    const validationResult = updateCompanySchema.safeParse(body);

    if (!validationResult.success) {
      const firstError = validationResult.error.issues[0];
      return NextResponse.json(
        {
          success: false,
          message: firstError?.message || "Validation failed",
        },
        { status: 400 }
      );
    }

    const updateData = validationResult.data;

    // Get company
    const company = await Company.findById(user.companyId);

    if (!company) {
      return NextResponse.json(
        {
          success: false,
          message: "Company not found",
        },
        { status: 404 }
      );
    }

    // Update company fields
    if (updateData.name && updateData.name !== company.name) {
      // Check if new name is unique
      const existingCompany = await Company.findOne({
        name: updateData.name,
        _id: { $ne: company._id },
      });

      if (existingCompany) {
        return NextResponse.json(
          {
            success: false,
            message: "Company name already exists",
          },
          { status: 409 }
        );
      }

      company.name = updateData.name;
      // Slug will be auto-generated by pre-save hook
    }

    if (updateData.domain !== undefined) {
      company.domain = updateData.domain || undefined;
    }

    if (updateData.settings) {
      company.settings = {
        ...company.settings,
        ...updateData.settings,
      };
    }

    await company.save();

    // Return updated company
    const updatedCompany = await Company.findById(company._id);

    return NextResponse.json({
      success: true,
      message: "Company updated successfully",
      company: {
        id: String(updatedCompany!._id),
        name: updatedCompany!.name,
        slug: updatedCompany!.slug,
        domain: updatedCompany!.domain,
        status: updatedCompany!.status,
        settings: updatedCompany!.settings,
        subscription: updatedCompany!.subscription,
        createdAt: updatedCompany!.createdAt.toISOString(),
        updatedAt: updatedCompany!.updatedAt.toISOString(),
      },
    });
  } catch (error) {
    console.error("Update company error:", error);
    return NextResponse.json(
      {
        success: false,
        message:
          error instanceof Error ? error.message : "Internal server error",
      },
      { status: 500 }
    );
  }
}

